// <auto-generated />
using System;
using CoreTemplate.Modules.Notificaciones.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreTemplate.Modules.Notificaciones.Infrastructure.Migrations
{
    [DbContext(typeof(NotificacionesDbContext))]
    [Migration("20260424151823_InitialCreate_Notificaciones")]
    partial class InitialCreate_Notificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Notificaciones")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreTemplate.Modules.Notificaciones.Domain.Aggregates.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EntregadaEnTiempoReal")
                        .HasColumnType("bit");

                    b.Property<bool>("EsLeida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeidaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UsuarioId")
                        .HasDatabaseName("IX_Notificaciones_TenantId_UsuarioId");

                    b.HasIndex("UsuarioId", "EsLeida")
                        .HasDatabaseName("IX_Notificaciones_UsuarioId_EsLeida");

                    b.ToTable("Notificaciones", "Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
